== Config

config your EKS cluster details in `terraform.tfvar` file

[source,note]
----
    region = "us-east-1"
    cluster_name = "my-eks"
    cluster_version = "1.19"
    vpc_name = "my-vpc"
    node_groups_name = "spot-1"
    instance_types = ["t3.medium","t3.small"]
    max_capacity = 2
    min_capacity= 1
    desired_capacity = 2
    capacity_type = "SPOT"
    k8s_labels = {
    environment = "dev"
----

== Terraform

=== Init

This is where you initialize your code to download the requirements
mentioned in your code

[source,bash]
----
/100-eks-cluster$ terraform init
----

=== Plan

This is where you review changes and choose whether to simply accept
them

[source,bash]
----
/100-eks-cluster$ terraform plan
----

=== Apply

This is where you accept changes and apply them against real
infrastructure

[source,bash]
----
/100-eks-cluster$ terraform apply
----

== aws-node-termination-handler

Suppose if have been choose spot instances, follow this
https://artifacthub.io/packages/helm/aws/aws-node-termination-handler[link]
to add aws-node-termination-handler to your pods. By using this you can
avoid your application downtime

== LB Config

[arabic]
. Create policy for AWS Load Balance Controller
. Create an IAM role for the AWS Load Balancer Controller with that
policy
. Update trusted-relationship policy for IAM role with EKS cluster
provider id
. Create service account with IAM role arn annotation
. Install the TargetGroupBinding custom resource definitions
. Add the eks-charts repository.
. Install the AWS Load Balancer Controller using the command that
corresponds to the Region that your cluster is in

[source,bash]
----
    helm upgrade -i aws-load-balancer-controller eks/aws-load-balancer-controller \
  --set clusterName=<cluster-name> \
  --set serviceAccount.create=false \
  --set serviceAccount.name=aws-load-balancer-controller \
  -n kube-system
----

https://docs.aws.amazon.com/eks/latest/userguide/aws-load-balancer-controller.html[more
info]

[arabic, start=8]
. Add public and private subnet tags
* Key – kubernetes.io/cluster/
* Value – shared or owned
. Add Private subnet tag
* Key – kubernetes.io/role/internal-elb
* Value – 1
. Add Private subnet tag
* Key – kubernetes.io/role/elb
* Value – 1
. Deploy your application with deployment, service ingress for ALB
https://docs.aws.amazon.com/eks/latest/userguide/alb-ingress.html[more
info]
. Deploy your application with deployment, service ingress for NLB
https://docs.aws.amazon.com/eks/latest/userguide/load-balancing.html[more
info]